import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

export const metadata: Metadata = {
  title: "Lynn's Book Marketplace",
  keywords: ["books", "marketplace", "used books", "buy books", "sell books", "trade books"],
  authors: [{ name: "Malik Snowden", url: "leeky.io" }],
  creator: "Lynn",
  publisher: "Lynn's Book Marketplace",
  openGraph: {
    title: "Lynn's Book Marketplace",
    description: "A marketplace for buying and selling used books",
    url: "books.leeky.io",
    siteName: "Lynn's Book Marketplace",
    images: [
      {
        url: "https://lynn-book-marketplace.example.com/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Lynn's Book Marketplace",
      },
    ],
  },
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>{children}</body>
    </html>
  );
}
